production: &production
  db1.username: "#required"
  db1.password: "#required"

staging: &staging
  db1.username: "#required"
  db1.password: "#required"

dimensions: &dimensions
  dimensions.username: "#required"
  dimensions.password: "#required"

samurai:
  metastore_username: "#required hive will not work without this property.  Please see operations if you do not know this"
  metastore_password: "#required hive will not work without this property.  Please see operations if you do not know this"
  <<: *production
  <<: *dimensions
