production: &production
  db1.username: bill
  db1.password: xxx123

staging: &staging
  db1.username: billy
  db1.password: 234567wr

dimensions: &dimensions
  dimensions.username: dim_user
  dimensions.password: sh1n345

samurai:
  metastore_username: meta_admin
  metastore_password: xxxxXxrr
  <<: *production
  <<: *dimensions
